import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = typeof window !== 'undefined' ? localStorage.getItem('user') : null;
  const isAuthenticated = user ? true : false;
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="./globals.css" />
      </head>
      <body>
        <Navbar isAuthenticated={isAuthenticated} />
        <main>{children}</main>
      </body>
    </html>
  );
}
